---
title: "resources"
subtitle: "a collection of other people's writings, tutorials, etc. that I find particularly helpful"
title-block-banner: true
---

It's finally time for an upgraded notebook! I've been Slacking myself (and subsequently burying) links to resources for far too long, so my favorites will now live here. 

## {{< fa book-open title="An open book" >}} learning materials

* Ever feel like you need a pick-me-up while learning stats or a new R tool? Look no further than [Allison Horst's](https://twitter.com/allison_horst) [Data Science Illustrations](https://allisonhorst.com/), featuring the cutest and most educational fuzzy monsters you'll ever see!

* [Mastering Shiny](https://mastering-shiny.org/index.html), by Hadley Wickham 

* [Happy Git and GitHub for the useR](https://happygitwithr.com/), by Jenny Bryan

* [R for Data Science](https://r4ds.had.co.nz/), by Hadley Wickham

* [Hitchhiker's Guide to Python](https://docs.python-guide.org/), by Kenneth Reitz & Tanya Schlusser

* [Data wrangling essentials: comparisons in JavaScript, Python, SQL, R, and Excel](https://observablehq.com/@observablehq/data-wrangling-translations), by Allison Horst & Paul Buffa

* [W3Schools](https://www.w3schools.com/default.asp), particularly for their HTML & CSS tutorials

## {{< fa chart-bar title="A bar chart" >}} data viz

* [from Data to Viz](https://www.data-to-viz.com/), a choose-your-adventure-type experience for creating your best data visualizations

* [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/), by Claus O. Wilke

* [The Sessions College Color Calculator](https://www.sessions.edu/color-calculator/), for creating color palettes

* [Beautifully Annotated: Enhancing your ggplots with Text](https://www.cararthompson.com/talks/rl-cambridge-beautifully-annotated/), by [Cara Thompson](https://www.cararthompson.com/about.html), a seriously wonderful talk on using annotations in your ggplots

## {{< fa tools title="A wrench and a screw driver" >}} r tools

* [free icons from fontawesome](https://fontawesome.com/v5/search?m=free) + the [`{fontawesome}`](https://github.com/rstudio/fontawesome) R package for infusing your slides, website, RMarkdowns/Quarto Markdowns, and more with an extra splash of fun

## {{< fa desktop title="A desktop computer screen" >}} reporting & presentations

* Quarto is all the rage these days (and by these days, I mean post-March 2022). Download and find some great tutorials [here](https://quarto.org/) to get started

* [Meet xaringan: Making slides in R Markdown](https://arm.rbind.io/slides/xaringan.html#1), by Allison Hill

* [Sharing Your `xaringan` Slides](https://www.garrickadenbuie.com/blog/sharing-xaringan-slides/), by Garrick Aden-Buie

## {{< fa users title="Three people" >}} data science communities

*While these groups are primarily based in SoCal/Santa Barbara, there are tons of awesome groups like these all over the world. Google around to see what's near you!*

* [R-Ladies Santa Barbara](https://www.meetup.com/rladies-santa-barbara/) and [R-Ladies Global](https://rladies.org/), which work to promote gender diversity in the R community  

* [EcoDataScience](https://eco-data-science.github.io/), an environmental data science study group at UCSB  
* [Southern California R Users](https://socalr.org/), an alliance of R user groups in Southern California  
* [Santa Barbara Women in STEM](https://www.sbwomeninstem.org/), while not specifically data science-focused, this group holds some really great career and networking events, panels, flash talks, and more

## {{< fa universal-access title="The Web Accessibility symbol, which is a person with outstretched arms inside a circle" >}} web accessibility

* [The A11Y Project](https://www.a11yproject.com/) is a community-driven effort to make digital content more accessible. I still have a long way to go in making my own website [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) compliant -- the A11Y Project not only has a ton of great blog posts, but also WCAG compliance checklist that I will definitely be returning to over and over again.  

* [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/), a color blindness simulator -- just upload a file and view your color palettes as they would appear under different types of color deficiencies

## {{< fa smile title="A smiling face" >}} misc.

* Discover new music to jam out to while you hack at [Every Noise at Once](https://everynoise.com/engenremap.html) (HT: Jeanette Clark)